-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.academy_profiles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid UNIQUE,
  academy_name character varying NOT NULL,
  offers_swimming boolean DEFAULT false,
  offers_fitness boolean DEFAULT false,
  registration_number character varying,
  description text,
  established_year integer,
  total_coaches integer,
  total_branches integer DEFAULT 1,
  facilities jsonb DEFAULT '[]'::jsonb,
  rating numeric DEFAULT 0.0,
  total_reviews integer DEFAULT 0,
  is_verified boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT academy_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT academy_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.analytics_events (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  event_type character varying NOT NULL,
  entity_id uuid NOT NULL,
  entity_type character varying NOT NULL,
  session_id uuid,
  ip_address inet,
  user_agent text,
  referrer text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT analytics_events_pkey PRIMARY KEY (id),
  CONSTRAINT analytics_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.analytics_summary (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  entity_id uuid NOT NULL,
  entity_type character varying NOT NULL,
  date date NOT NULL,
  views_count integer DEFAULT 0,
  unique_views_count integer DEFAULT 0,
  inquiries_count integer DEFAULT 0,
  shares_count integer DEFAULT 0,
  saves_count integer DEFAULT 0,
  CONSTRAINT analytics_summary_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cities (
  id integer NOT NULL DEFAULT nextval('cities_id_seq'::regclass),
  governorate_id integer,
  name_en character varying NOT NULL,
  name_ar character varying NOT NULL,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  CONSTRAINT cities_pkey PRIMARY KEY (id),
  CONSTRAINT cities_governorate_id_fkey FOREIGN KEY (governorate_id) REFERENCES public.governorates(id)
);
CREATE TABLE public.coach_profiles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid UNIQUE,
  offers_swimming boolean DEFAULT false,
  offers_fitness boolean DEFAULT false,
  years_experience integer,
  certifications jsonb DEFAULT '[]'::jsonb,
  specializations jsonb DEFAULT '[]'::jsonb,
  achievements jsonb DEFAULT '[]'::jsonb,
  rating numeric DEFAULT 0.0,
  total_reviews integer DEFAULT 0,
  response_time_minutes integer,
  is_verified boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT coach_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT coach_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.conversations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  participant_1_id uuid,
  participant_2_id uuid,
  related_listing_id uuid,
  related_listing_type character varying,
  is_active boolean DEFAULT true,
  last_message_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT conversations_pkey PRIMARY KEY (id),
  CONSTRAINT conversations_participant_2_id_fkey FOREIGN KEY (participant_2_id) REFERENCES auth.users(id),
  CONSTRAINT conversations_participant_1_id_fkey FOREIGN KEY (participant_1_id) REFERENCES auth.users(id)
);
CREATE TABLE public.email_verification_codes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  code character varying NOT NULL,
  email character varying NOT NULL,
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '00:05:00'::interval),
  is_used boolean DEFAULT false,
  used_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_verification_codes_pkey PRIMARY KEY (id),
  CONSTRAINT email_verification_codes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.governorates (
  id integer NOT NULL DEFAULT nextval('governorates_id_seq'::regclass),
  name_en character varying NOT NULL,
  name_ar character varying NOT NULL,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  CONSTRAINT governorates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.locations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  entity_id uuid NOT NULL,
  entity_type character varying NOT NULL,
  governorate_id integer,
  city_id integer,
  area_name character varying,
  venue_name character varying,
  address_line text,
  google_maps_url text,
  coordinates point,
  is_primary boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT locations_pkey PRIMARY KEY (id),
  CONSTRAINT locations_governorate_id_fkey FOREIGN KEY (governorate_id) REFERENCES public.governorates(id),
  CONSTRAINT locations_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.cities(id)
);
CREATE TABLE public.marketplace_categories (
  id integer NOT NULL DEFAULT nextval('marketplace_categories_id_seq'::regclass),
  category USER-DEFINED NOT NULL,
  subcategory character varying NOT NULL,
  name_en character varying NOT NULL,
  name_ar character varying NOT NULL,
  icon character varying,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  CONSTRAINT marketplace_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.marketplace_listings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  seller_id uuid,
  seller_role USER-DEFINED CHECK (seller_role = ANY (ARRAY['customer'::user_role_type, 'reseller'::user_role_type, 'vendor'::user_role_type])),
  title character varying NOT NULL,
  description text,
  category_id integer,
  price numeric NOT NULL,
  currency character varying DEFAULT 'EGP'::character varying,
  condition USER-DEFINED NOT NULL,
  quantity_available integer DEFAULT 1,
  item_attributes jsonb DEFAULT '{}'::jsonb,
  images jsonb DEFAULT '[]'::jsonb,
  video_url text,
  accepts_online_payment boolean DEFAULT false,
  shipping_available boolean DEFAULT false,
  shipping_costs jsonb,
  is_active boolean DEFAULT true,
  is_sold boolean DEFAULT false,
  is_promoted boolean DEFAULT false,
  promoted_until timestamp with time zone,
  view_count integer DEFAULT 0,
  inquiry_count integer DEFAULT 0,
  listing_expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT marketplace_listings_pkey PRIMARY KEY (id),
  CONSTRAINT marketplace_listings_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.marketplace_categories(id),
  CONSTRAINT marketplace_listings_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES auth.users(id)
);
CREATE TABLE public.marketplace_revenue_tracking (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  listing_id uuid,
  cost_price numeric,
  selling_price numeric,
  profit numeric DEFAULT (selling_price - cost_price),
  sold_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT marketplace_revenue_tracking_pkey PRIMARY KEY (id),
  CONSTRAINT marketplace_revenue_tracking_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT marketplace_revenue_tracking_listing_id_fkey FOREIGN KEY (listing_id) REFERENCES public.marketplace_listings(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  conversation_id uuid,
  sender_id uuid,
  message_text text,
  attachments jsonb DEFAULT '[]'::jsonb,
  is_read boolean DEFAULT false,
  read_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id),
  CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES auth.users(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  payment_for character varying NOT NULL,
  related_id uuid,
  amount numeric NOT NULL,
  currency character varying DEFAULT 'EGP'::character varying,
  payment_method character varying,
  gateway_payment_id character varying,
  gateway_response jsonb,
  status character varying DEFAULT 'pending'::character varying,
  paid_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  full_name character varying NOT NULL,
  email character varying NOT NULL UNIQUE,
  phone character varying,
  avatar_url text,
  bio text,
  is_email_verified boolean DEFAULT false,
  email_verified_at timestamp with time zone,
  account_status character varying DEFAULT 'active'::character varying,
  preferred_language character varying DEFAULT 'ar'::character varying,
  notification_preferences jsonb DEFAULT '{"sms": false, "push": true, "email": true}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.promotions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  listing_id uuid NOT NULL,
  listing_type character varying NOT NULL,
  promoted_from timestamp with time zone DEFAULT now(),
  promoted_until timestamp with time zone DEFAULT (now() + '7 days'::interval),
  price_paid numeric NOT NULL,
  was_free boolean DEFAULT false,
  additional_views integer DEFAULT 0,
  additional_inquiries integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT promotions_pkey PRIMARY KEY (id),
  CONSTRAINT promotions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.rehab_listings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  provider_id uuid,
  service_name character varying NOT NULL,
  description text,
  therapy_type USER-DEFINED NOT NULL,
  conditions_treated jsonb DEFAULT '[]'::jsonb,
  session_duration_minutes integer NOT NULL,
  price_per_session numeric NOT NULL,
  currency character varying DEFAULT 'EGP'::character varying,
  equipment_available jsonb DEFAULT '[]'::jsonb,
  images jsonb DEFAULT '[]'::jsonb,
  video_url text,
  has_online_booking boolean DEFAULT false,
  is_active boolean DEFAULT true,
  is_promoted boolean DEFAULT false,
  promoted_until timestamp with time zone,
  view_count integer DEFAULT 0,
  inquiry_count integer DEFAULT 0,
  listing_expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT rehab_listings_pkey PRIMARY KEY (id),
  CONSTRAINT rehab_listings_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES auth.users(id)
);
CREATE TABLE public.rehab_provider_profiles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid UNIQUE,
  clinic_name character varying NOT NULL,
  license_number character varying,
  description text,
  specializations jsonb DEFAULT '[]'::jsonb,
  equipment_available jsonb DEFAULT '[]'::jsonb,
  rating numeric DEFAULT 0.0,
  total_reviews integer DEFAULT 0,
  total_patients integer DEFAULT 0,
  is_verified boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT rehab_provider_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT rehab_provider_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.reseller_profiles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid UNIQUE,
  business_name character varying,
  description text,
  specializes_in jsonb DEFAULT '[]'::jsonb,
  rating numeric DEFAULT 0.0,
  total_reviews integer DEFAULT 0,
  total_sales integer DEFAULT 0,
  is_verified boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reseller_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT reseller_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.reviews (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  reviewer_id uuid,
  reviewed_entity_id uuid NOT NULL,
  reviewed_entity_type character varying NOT NULL,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  review_text text,
  is_verified_purchase boolean DEFAULT false,
  response_text text,
  response_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reviews_pkey PRIMARY KEY (id),
  CONSTRAINT reviews_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES auth.users(id)
);
CREATE TABLE public.service_listings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  provider_id uuid,
  provider_role USER-DEFINED CHECK (provider_role = ANY (ARRAY['coach'::user_role_type, 'academy'::user_role_type])),
  title character varying NOT NULL,
  description text,
  service_type USER-DEFINED NOT NULL,
  price_per_session numeric NOT NULL,
  currency character varying DEFAULT 'EGP'::character varying,
  age_group USER-DEFINED DEFAULT 'all_ages'::age_group,
  skill_level USER-DEFINED DEFAULT 'all'::skill_level,
  gender_preference USER-DEFINED DEFAULT 'mixed'::gender_preference,
  max_participants integer,
  duration_minutes integer NOT NULL,
  schedule_data jsonb NOT NULL,
  images jsonb DEFAULT '[]'::jsonb,
  video_url text,
  is_active boolean DEFAULT true,
  is_promoted boolean DEFAULT false,
  promoted_until timestamp with time zone,
  view_count integer DEFAULT 0,
  inquiry_count integer DEFAULT 0,
  listing_expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT service_listings_pkey PRIMARY KEY (id),
  CONSTRAINT service_listings_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES auth.users(id)
);
CREATE TABLE public.spatial_ref_sys (
  srid integer NOT NULL CHECK (srid > 0 AND srid <= 998999),
  auth_name character varying,
  auth_srid integer,
  srtext character varying,
  proj4text character varying,
  CONSTRAINT spatial_ref_sys_pkey PRIMARY KEY (srid)
);
CREATE TABLE public.subscription_configs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  role_type USER-DEFINED NOT NULL,
  plan USER-DEFINED NOT NULL,
  price_monthly numeric DEFAULT 0,
  price_annual numeric DEFAULT 0,
  max_listings integer,
  max_active_listings integer,
  max_photos_per_listing integer DEFAULT 3,
  max_videos_per_listing integer DEFAULT 0,
  listing_duration_days integer DEFAULT 30,
  has_verified_badge boolean DEFAULT false,
  has_analytics boolean DEFAULT false,
  has_revenue_tracking boolean DEFAULT false,
  free_promotions_per_month integer DEFAULT 0,
  promotion_price numeric,
  priority_in_search integer DEFAULT 0,
  has_online_payments boolean DEFAULT false,
  has_shipping_integration boolean DEFAULT false,
  has_inventory_management boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscription_configs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_roles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  role USER-DEFINED NOT NULL,
  is_active boolean DEFAULT true,
  is_primary boolean DEFAULT false,
  enrolled_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_roles_pkey PRIMARY KEY (id),
  CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_subscriptions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  role USER-DEFINED NOT NULL,
  plan USER-DEFINED NOT NULL DEFAULT 'free'::subscription_plan,
  status USER-DEFINED NOT NULL DEFAULT 'active'::subscription_status,
  billing_cycle USER-DEFINED,
  started_at timestamp with time zone DEFAULT now(),
  current_period_start timestamp with time zone DEFAULT now(),
  current_period_end timestamp with time zone,
  cancelled_at timestamp with time zone,
  price_paid numeric DEFAULT 0,
  listings_count integer DEFAULT 0,
  promotions_used_this_month integer DEFAULT 0,
  last_promotion_reset date DEFAULT CURRENT_DATE,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT user_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.vendor_profiles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid UNIQUE,
  store_name character varying NOT NULL,
  registration_number character varying,
  tax_number character varying,
  description text,
  logo_url text,
  cover_image_url text,
  specializes_in jsonb DEFAULT '[]'::jsonb,
  rating numeric DEFAULT 0.0,
  total_reviews integer DEFAULT 0,
  total_sales integer DEFAULT 0,
  has_physical_store boolean DEFAULT false,
  store_addresses jsonb DEFAULT '[]'::jsonb,
  is_verified boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT vendor_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT vendor_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.verification_code_attempts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid UNIQUE,
  email character varying NOT NULL,
  last_sent_at timestamp with time zone DEFAULT now(),
  total_sent_today integer DEFAULT 1,
  attempts_date date DEFAULT CURRENT_DATE,
  CONSTRAINT verification_code_attempts_pkey PRIMARY KEY (id),
  CONSTRAINT verification_code_attempts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);